### ISSUE TITLE
Client Authentication required, setting a Client secret

### ISSUE THREAD

**Issue by mrudatsprint** [FusionAuth/fusionauth-android-sdk#129]
### Problem
I'm unable to set the client secret to receive an access token when the FusionAuth application is configured with Client Authentication set to required.  There doesn't appear to be a way to set the client secret.

### Solution
Allow support for a clientSecret in the AuthorizationConfiguration.

### Alternatives/workarounds
The FusionAuth application sets Client Authentication to Not required.  Use [AppAuth](https://github.com/openid/AppAuth-Android) directly.

### Additional context
authService.performTokenRequest in [OAuthAuthorizationService.kt](https://github.com/FusionAuth/fusionauth-android-sdk/blob/be261cc934972ec98c6d178423e43d1a5c85a51c/library/src/main/java/io/fusionauth/mobilesdk/oauth/OAuthAuthorizationService.kt#L341) does not allow for a ClientAuthentication to be set and passed in.  appAuthState.clientAuthentication defaults to NoClientAuthentication.

Ideally we want to set a ClientAuthentication such as the example in [AppAuth Documentation](https://github.com/openid/AppAuth-Android/blob/master/README.md#utilizing-client-secrets-dangerous) before calling performTokenRequest.

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by mrudatsprint** [comment]
@Aaron-Ritter Is the thought that maybe the client secret can't be set as mobile applications require additional security in implementing the Authorization Code Grant flow due to the inability to safely store a client secret?   Thus, setting the client secret wasn't implemented in the SDK and the recommendation is to use PKCE.

**Comment by ColinFrick** [comment]
Hi @mrudatsprint 

As stated in the linked AppAuth README section:
> We strongly recommend you avoid using static client secrets in your native applications whenever possible. 

That's the reason Client Authentication was not implemented in the SDK. Authorization Code Grant Flow with PKCE is the recommended way for "public clients" like native or mobile apps.

**Comment by mrudatsprint** [comment]
Hi @ColinFrick,

I'm setting up PKCE using a codeChallenge and codeChallengeMethod and getting an exception:

`
2024-12-03 15:50:52.220 10482-10482 AndroidRuntime          io.fusionauth.app                    E  FATAL EXCEPTION: main
Process: io.fusionauth.app, PID: 10482
java.lang.IllegalArgumentException: Parameter code_challenge is directly supported via the authorization request builder, use the builder method instead
   at net.openid.appauth.Preconditions.checkArgument(Preconditions.java:132)
`

It appears AppAuth requires this to be done using a builder API setCodeVerifier instead of additional parameters.  Is there a working example of setting up PKCE using the code_challenge and code_challenge_method parameters?

**Comment by ColinFrick** [comment]
Hi @mrudatsprint 

You shouldn't have to do anything in your Android app. PKCE is used by default with a random generated string.
What is your requirement to set the `code_challenge` and `code_challenge_method` manually? The only reason I can think of is disabling PKCE completely.

But you are right, that having the option to set `codeChallenge` and `codeChallengeMethod` in the `OAuthAuthorizeOptions` is confusing, and clearly doesn't work.

You also can set `PKCE` to `Required` on FusionAuth in your application under the `OAuth` tab.

**Comment by mrudatsprint** [comment]
@ColinFrick Thank you for helping me understand that PKCE and the code_challenge are built into the SDK.  I've been working with a customer who was trying to set the code_challenge and code_challenge_method.  I'm going to close the issue.

**Comment by Aaron-Ritter** [comment]
Thanks @mrudatsprint ! I've created an issue to Remove codeChallenge and codeChallengeMethod from OAuthAuthorizeOptions #130 as the current implementation is not working and leads to confusion.
