### ISSUE TITLE
Firefox, cancel "Open in another app" window prevents login from continuing and on subsequent attempts

### ISSUE THREAD

**Issue by mrudatsprint** [FusionAuth/fusionauth-android-sdk#133]
### Description 
When logging in using Firefox, the "Open in another app" modal is presented to the user.  If CANCEL is selected then the login workflow will stop and all subsequent login attempts will fail with a blank screen.

### Affects versions
0.1.7

### Steps to reproduce
1. Using the [FusionAuth QuickStart](https://github.com/FusionAuth/fusionauth-quickstart-kotlin-android-native)
2. Click on 'LOG IN'
3. The Login screen is displayed.
4. Enter the Email, Password and Click on 'SUBMIT'
5. The 'Open in another app' window is displayed
6. Click on 'CANCEL'
7. A blank screen is dispayed
8. Go back to the 'LOG IN' screen
9. Click on 'LOG IN'
10. A blank screen is displayed

### Expected behavior
Selecting CANCEL on the "Open in another app' window should allow the login process to stop and be re-started so the user can select OPEN to continue the login.

### Screenshots
A video of the behavior.  
[login.webm](https://github.com/user-attachments/assets/5d7d03d1-e347-44cd-922e-fb61f079c93d)

The 'Open in another app' window.
<img width="307" alt="Screenshot 2024-12-10 at 2 17 15 PM" src="https://github.com/user-attachments/assets/eea1f5cc-c960-476c-b1c9-9051a5bb0c84" />

### Platform
(Please complete the following information)
 - Device: [Android Studio Emulator Pixel 9 Pro XL API 35]
 - OS: [Android]
 - Default Mobile Browser + version [Firefox 133.0.2]
 - FusionAuth version [1.54.0]

### Community guidelines
All issues filed in this repository must abide by the [FusionAuth community guidelines](https://fusionauth.io/community/forum/topic/1000/code-of-conduct).

### Additional context
The default behavior in Firefox after I downloaded it to the emulator was to never open links in apps.  The issue can be fixed by:

In Firefox:
1. set Settings->Advanced->Open links in apps to Always.
2. Settings->Delete browsing data
3. Clear all and re-start the android application

**Comment by Aaron-Ritter** [comment]
Thanks @mrudatsprint, Question about the Steps, does it redirect back to the App if you press **OPEN** (without any modifications to the firefox browser setting).

**Comment by mrudatsprint** [comment]
@Aaron-Ritter Yes, the user is successfully logged in if OPEN is pressed

**Comment by Aaron-Ritter** [comment]
Possibly related:
https://bugzilla.mozilla.org/show_bug.cgi?id=1847273

But the mentioned workarounds to resurface the 'Open in another app' window seem not to be possible in this use case.

Sidenote: https://github.com/mozilla-mobile/firefox-android [migrated](https://github.com/mozilla-mobile/firefox-android/wiki#upcoming-migration-to-mozilla-central) to [Mozilla Central](https://hg.mozilla.org/mozilla-central)

**Comment by Aaron-Ritter** [comment]
@mrudatsprint we reproduced the issue and have a few findings so far:

- The in-app browser caches information independently from the browser app, so if you cancel you could use the three dot menu in the in-app browser and get the popup once more in the firefox app.
- We hand test constellations where we ended the quickstart app and/or the browser app and it was able to show the popup once more (one suggestion which can be found in https://bugzilla.mozilla.org/show_bug.cgi?id=1847273) but couldn't consistently reproduce it yet.

We discussed another possibility of forcing or blacklisting certain browsers as documented here https://github.com/openid/AppAuth-Android?tab=readme-ov-file#controlling-which-browser-is-used-for-authorization but don't recommend it. This should be rather used as a possiblity to avoid browsers with bugs or security risks. And generally there is a free choice of system browser so if you force a browser which isn't the default browser you could introduce friction in other flows which e.g. use the same auth backend.

Once I did a few more tests I'll open a case with mozilla.

**Comment by Aaron-Ritter** [comment]
@mrudatsprint i reproduced a consitent flow to reset and resurface the dialog box:

Once you hit cancel you can do the following:
1. Close the App Process
2. If Firefox is not already running start Firefox App
3. Close the Firefox App Process
4. Start the App Process and the OAuth flow will show the 'Open in another app' dialog again

[reset-redirect-popup-firefox.webm](https://github.com/user-attachments/assets/1bc778a8-de48-44ee-ba7d-8c0887b165ab)

Why it isn't enough to only close the app i am not sure, and we could open a issue with Mozilla but at least it confirms partially the workaround mentioned in https://bugzilla.mozilla.org/show_bug.cgi?id=1847273 that this choice only gest stored in memory and not permanently.

**Comment by mrudatsprint** [comment]
Thank you @Aaron-Ritter That sequence did work provided I changed In Firefox:

Set Settings->Advanced->Open links in apps to Always or Ask before opening

The default value in the emulator in Android Studio is never.  I wish that I had an Android phone to verify the default Firefox setting for Open links in apps.

Thank You

**Comment by Aaron-Ritter** [comment]
Thanks @mrudatsprint.

The configuration we used was a fresh android emulator image with the latest firefox version.

<img width="352" alt="Screenshot 2024-12-18 at 10 37 50" src="https://github.com/user-attachments/assets/469fcb4f-223b-45b4-be4f-1b3eda325d1c" />

The default configuration in this version is **Never** and thats the one i tested with.

<img width="217" alt="Screenshot 2024-12-18 at 10 38 02" src="https://github.com/user-attachments/assets/663743f6-237f-48f1-9241-35833470dd49" />

And as stated in Mozilla support this is the default setting https://support.mozilla.org/en-US/kb/set-firefox-android-open-links-native-apps

There should be no concern that the emulator handles this differently, and as long a user uses the latest firefox and did not do any manual configuration we should be expecting the same behaviour.

**Comment by mrudatsprint** [comment]
Awesome @Aaron-Ritter I have confirmed the workaround and I'll report back to the customer.  Thank you so much!

**Comment by Aaron-Ritter** [comment]
great! i close this issue for now :+1:
